// Copyright 2026 [Copyright Holder]
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Author: [YOUR_NAME]

package discover

import "time"

// BinaryMeta holds static inspection metadata of an application binary.
type BinaryMeta struct {
	Size         int64  `json:"size" yaml:"size"`
	SHA256       string `json:"sha256" yaml:"sha256"`
	Architecture string `json:"architecture,omitempty" yaml:"architecture,omitempty"`
	Type         string `json:"type,omitempty" yaml:"type,omitempty"` // e.g. "ELF Go", "ELF Native", "Script"
}

// PlanService defines a discovered systemd service candidate for migration.
type PlanService struct {
	Name        string      `json:"name" yaml:"name"`
	Binary      string      `json:"binary" yaml:"binary"`
	Configs     []string    `json:"configs,omitempty" yaml:"configs,omitempty"`
	Ingest      bool        `json:"ingest" yaml:"ingest"` // true: Mode A (Local Ingestion), false: Mode B (TODO Hint)
	UnitFile    string      `json:"unitFile,omitempty" yaml:"unitFile,omitempty"`
	Description string      `json:"description,omitempty" yaml:"description,omitempty"`
	BinaryInfo  *BinaryMeta `json:"binaryInfo,omitempty" yaml:"binaryInfo,omitempty"`
}

// PlanCustomDir defines an optional static directory for inclusion.
type PlanCustomDir struct {
	Path        string `json:"path" yaml:"path"`
	Permissions string `json:"permissions,omitempty" yaml:"permissions,omitempty"`
}

// PlanTargets groups candidate components discovered on the server.
type PlanTargets struct {
	Services   []PlanService   `json:"services,omitempty" yaml:"services,omitempty"`
	CustomDirs []PlanCustomDir `json:"customDirs,omitempty" yaml:"customDirs,omitempty"`
}

// DiscoveryPlan represents the intermediate, single-source-of-truth whitelist plan
// generated by `ytagarasu discover survey` and reviewed by human operators.
type DiscoveryPlan struct {
	Version   string      `json:"version" yaml:"version"`
	CreatedAt time.Time   `json:"createdAt" yaml:"createdAt"`
	Hostname  string      `json:"hostname,omitempty" yaml:"hostname,omitempty"`
	Targets   PlanTargets `json:"targets" yaml:"targets"`
}
